partial class LocalKey {
    public const string PLAYER_PROFILE_USERNAME = "PLAYER_PROFILE_USERNAME";
    public const string PLAYER_PROFILE_DESCRIPTION = "PLAYER_PROFILE_DESCRIPTION";
    public const string PLAYER_PROFILE_NUMKILL = "PLAYER_PROFILE_NUMKILL";
    public const string PLAYER_PROFILE_NUMDEATH = "PLAYER_PROFILE_NUMDEATH";
    public const string PLAYER_PROFILE_NUMASSIST = "PLAYER_PROFILE_NUMASSIST";
    public const string PLAYER_PROFILE_CURRANKPOINT = "PLAYER_PROFILE_CURRANKPOINT";
    public const string PLAYER_PROFILE_HIGHESTRANKPOINT = "PLAYER_PROFILE_HIGHESTRANKPOINT";
}